#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y update
sudo apt-get install -y haproxy=2.4.\*

# Use sudo to write to /etc/default/haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Listen to web1 and web2 servers
# Use sudo to write to /etc/haproxy/haproxy.cfg
sudo bash -c 'cat << EOF >> /etc/haproxy/haproxy.cfg
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 500392-web-01 100.25.14.217:80 check
    server 500392-web-02 107.23.90.175:80 check
EOF'

sudo service haproxy start

